/**
 * The operator's sample book of business: ten fictional client businesses.
 * Names, people and figures are invented for the demo; any resemblance to a
 * real company is coincidental.
 *
 * Plans come from content/pricing.ts. Enterprise has no list price, so the
 * Enterprise sample client carries an explicit sample contract value.
 */

import type { Client, PlanChange } from './types.ts'
import { atLocal } from './time.ts'

const email = (name: string, domain: string) =>
  `${name.toLowerCase().replace(/^dr\.\s*/, '').split(' ')[0]}@${domain}`

export const FEATURED_CLIENT_ID = 'juniper-row'

export const clients: Client[] = [
  {
    id: 'juniper-row',
    name: 'Juniper Row Realty',
    short: 'Juniper Row',
    industry: 'Real estate',
    kit: 'real-estate',
    plan: 'scale',
    status: 'active',
    since: atLocal(2026, 1, 3),
    location: 'Charleston, SC',
    billingDay: 8,
    team: [
      { name: 'Dana Whitfield', role: 'Owner · Broker', email: email('Dana Whitfield', 'juniperrow.example') },
      { name: 'Marcus Bell', role: 'Buyer’s agent', email: email('Marcus Bell', 'juniperrow.example') },
      { name: 'Priya Raman', role: 'Listing agent', email: email('Priya Raman', 'juniperrow.example') },
      { name: 'Elena Soto', role: 'Transaction coordinator', email: email('Elena Soto', 'juniperrow.example') },
    ],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'attention',
      'phone-text': 'connected',
      webhooks: 'available',
      spreadsheet: 'connected',
    },
    rate: 3.9,
    trend: 0.18,
    replyRate: 0.58,
    pool: 210,
    waves: [
      { from: 80, to: 72, share: 0.22 },
      { from: 46, to: 36, share: 0.3 },
      { from: 16, to: 0, share: 0.48 },
    ],
  },
  {
    id: 'blue-heron',
    name: 'Blue Heron Property Group',
    short: 'Blue Heron',
    industry: 'Real estate',
    kit: 'real-estate',
    plan: 'enterprise',
    contractMonthly: 3200,
    status: 'active',
    since: atLocal(2025, 10, 12),
    location: 'Tampa, FL · 3 offices',
    billingDay: 12,
    team: [
      { name: 'Colette Marsh', role: 'Managing broker', email: email('Colette Marsh', 'blueheron.example') },
      { name: 'Andre Whitley', role: 'Leasing director', email: email('Andre Whitley', 'blueheron.example') },
      { name: 'Sun-Hee Park', role: 'Operations manager', email: email('Sun-Hee Park', 'blueheron.example') },
      { name: 'Tomas Rivera', role: 'Agent', email: email('Tomas Rivera', 'blueheron.example') },
      { name: 'Brianna Cole', role: 'Agent', email: email('Brianna Cole', 'blueheron.example') },
    ],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'connected',
      spreadsheet: 'connected',
    },
    rate: 8.2,
    trend: 0.06,
    replyRate: 0.58,
    pool: 260,
    waves: [
      { from: 88, to: 60, share: 0.5 },
      { from: 30, to: 0, share: 0.5 },
    ],
  },
  {
    id: 'bellwether',
    name: 'Bellwether Heating & Air',
    short: 'Bellwether',
    industry: 'Home services',
    kit: 'hvac',
    plan: 'scale',
    status: 'active',
    since: atLocal(2025, 7, 19),
    location: 'Columbus, OH',
    billingDay: 19,
    team: [
      { name: 'Gary Lindqvist', role: 'Owner', email: email('Gary Lindqvist', 'bellwetherair.example') },
      { name: 'Renee Callahan', role: 'Office manager', email: email('Renee Callahan', 'bellwetherair.example') },
      { name: 'Luis Batista', role: 'Service lead', email: email('Luis Batista', 'bellwetherair.example') },
    ],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'attention',
      spreadsheet: 'connected',
    },
    rate: 6.1,
    trend: 0.22,
    replyRate: 0.61,
    pool: 180,
    waves: [{ from: 40, to: 20, share: 1 }],
  },
  {
    id: 'crescent-ridge',
    name: 'Crescent Ridge Roofing',
    short: 'Crescent Ridge',
    industry: 'Home services',
    kit: 'roofing',
    plan: 'core',
    status: 'active',
    statusNote: 'Website form has not sent a lead since Sep 3.',
    since: atLocal(2026, 2, 2),
    location: 'Raleigh, NC',
    billingDay: 2,
    team: [{ name: 'Wade Holcomb', role: 'Owner', email: email('Wade Holcomb', 'crescentridge.example') }],
    integrations: {
      'web-forms': 'attention',
      'landing-pages': 'connected',
      crm: 'available',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'available',
      spreadsheet: 'available',
    },
    rate: 2,
    trend: -0.5,
    replyRate: 0.34,
    pool: 60,
    waves: [{ from: 60, to: 50, share: 1 }],
  },
  {
    id: 'solstice',
    name: 'Solstice Skin & Laser',
    short: 'Solstice',
    industry: 'Med spa',
    kit: 'med-spa',
    plan: 'scale',
    status: 'active',
    since: atLocal(2025, 9, 6),
    location: 'Scottsdale, AZ',
    billingDay: 6,
    team: [
      { name: 'Dr. Lena Vogel', role: 'Medical director', email: email('Dr. Lena Vogel', 'solsticeskin.example') },
      { name: 'Kiara Jensen', role: 'Front desk lead', email: email('Kiara Jensen', 'solsticeskin.example') },
      { name: 'Mia Castellanos', role: 'Aesthetician', email: email('Mia Castellanos', 'solsticeskin.example') },
    ],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'connected',
      spreadsheet: 'available',
    },
    rate: 5,
    trend: 0.1,
    replyRate: 0.64,
    pool: 140,
    waves: [
      { from: 85, to: 80, share: 0.4 },
      { from: 21, to: 14, share: 0.6 },
    ],
  },
  {
    id: 'marigold',
    name: 'Marigold Aesthetics',
    short: 'Marigold',
    industry: 'Med spa',
    kit: 'med-spa',
    plan: 'growth',
    status: 'onboarding',
    statusNote: 'Onboarding since Sep 8 · calendar not connected yet.',
    since: atLocal(2026, 8, 8),
    location: 'Austin, TX',
    billingDay: 8,
    team: [{ name: 'Alana Brooks', role: 'Owner', email: email('Alana Brooks', 'marigoldaesthetics.example') }],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'available',
      calendar: 'available',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'available',
      spreadsheet: 'connected',
    },
    rate: 2.9,
    trend: 0,
    replyRate: 0.55,
    pool: 40,
    waves: [{ from: 12, to: 4, share: 1 }],
  },
  {
    id: 'calder-wynn',
    name: 'Calder Wynn Law',
    short: 'Calder Wynn',
    industry: 'Law',
    kit: 'law',
    plan: 'scale',
    status: 'active',
    since: atLocal(2025, 5, 23),
    location: 'Denver, CO',
    billingDay: 23,
    team: [
      { name: 'Nathaniel Calder', role: 'Managing partner', email: email('Nathaniel Calder', 'calderwynn.example') },
      { name: 'Sophie Wynn', role: 'Partner', email: email('Sophie Wynn', 'calderwynn.example') },
      { name: 'Rosa Delacroix', role: 'Intake specialist', email: email('Rosa Delacroix', 'calderwynn.example') },
      { name: 'Ben Ashford', role: 'Paralegal', email: email('Ben Ashford', 'calderwynn.example') },
    ],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'connected',
      webhooks: 'available',
      spreadsheet: 'available',
    },
    rate: 3.3,
    trend: 0.08,
    replyRate: 0.57,
    pool: 90,
    waves: [{ from: 50, to: 35, share: 1 }],
  },
  {
    id: 'fieldnote',
    name: 'Fieldnote Creative',
    short: 'Fieldnote',
    industry: 'Agency',
    kit: 'agency',
    plan: 'growth',
    status: 'active',
    since: atLocal(2026, 0, 14),
    location: 'Portland, OR',
    billingDay: 14,
    team: [{ name: 'Ivy Sorensen', role: 'Founder', email: email('Ivy Sorensen', 'fieldnote.example') }],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'available',
      crm: 'connected',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'available',
      webhooks: 'available',
      spreadsheet: 'available',
    },
    rate: 1.2,
    trend: 0.15,
    replyRate: 0.6,
    pool: 40,
    waves: [{ from: 30, to: 24, share: 1 }],
  },
  {
    id: 'tallyhouse',
    name: 'Tallyhouse Software',
    short: 'Tallyhouse',
    industry: 'SaaS',
    kit: 'saas',
    plan: 'core',
    status: 'paused',
    statusNote: 'Paused Sep 12 after two failed payments. Automations are stopped.',
    since: atLocal(2025, 11, 1),
    location: 'Minneapolis, MN',
    billingDay: 1,
    team: [{ name: 'Priyanka Desai', role: 'Head of growth', email: email('Priyanka Desai', 'tallyhouse.example') }],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'available',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'available',
      webhooks: 'available',
      spreadsheet: 'available',
    },
    rate: 2.1,
    trend: 0,
    replyRate: 0.5,
    pool: 70,
    waves: [{ from: 70, to: 60, share: 1 }],
    paused: { at: atLocal(2026, 8, 12, 9, 0), reason: 'Two failed payments' },
  },
  {
    id: 'wren-loom',
    name: 'Wren & Loom Goods',
    short: 'Wren & Loom',
    industry: 'E-commerce',
    kit: 'ecommerce',
    plan: 'core',
    status: 'active',
    since: atLocal(2026, 3, 20),
    location: 'Asheville, NC',
    billingDay: 20,
    team: [{ name: 'Hattie Morrow', role: 'Founder', email: email('Hattie Morrow', 'wrenandloom.example') }],
    integrations: {
      'web-forms': 'connected',
      'landing-pages': 'connected',
      crm: 'available',
      calendar: 'connected',
      'email-inbox': 'connected',
      'phone-text': 'available',
      webhooks: 'available',
      spreadsheet: 'connected',
    },
    rate: 2.2,
    trend: 0.12,
    replyRate: 0.47,
    pool: 110,
    waves: [
      { from: 62, to: 55, share: 0.5 },
      { from: 9, to: 2, share: 0.5 },
    ],
  },
]

export const clientById = (id: string) => clients.find((client) => client.id === id)

/** Plan history. The billing views derive upgrades, downgrades and invoice amounts from it. */
export const planChanges: PlanChange[] = [
  { id: 'pc-1', clientId: 'blue-heron', from: 'scale', to: 'enterprise', at: atLocal(2026, 4, 1, 10) },
  { id: 'pc-2', clientId: 'calder-wynn', from: 'growth', to: 'scale', at: atLocal(2026, 6, 14, 15) },
  { id: 'pc-3', clientId: 'juniper-row', from: 'growth', to: 'scale', at: atLocal(2026, 7, 5, 11) },
  { id: 'pc-4', clientId: 'wren-loom', from: 'growth', to: 'core', at: atLocal(2026, 7, 20, 16) },
  { id: 'pc-5', clientId: 'solstice', from: 'growth', to: 'scale', at: atLocal(2026, 8, 3, 9) },
]
